; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "Pino Launcher"
!define PRODUCT_VERSION "0.7.0"
!define PRODUCT_PUBLISHER "Mix Dev Studios"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\Launcher.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "pino_settings.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\Launcher.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "Spanish"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "PinoInstaller.exe"
InstallDir "$PROGRAMFILES\Pino Launcher"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Section "Principal" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite ifnewer
  File ".\bin\Release\net8.0\publish\win-x64\av_libglesv2.dll"
  File ".\bin\Release\net8.0\publish\win-x64\libHarfBuzzSharp.dll"
  File ".\bin\Release\net8.0\publish\win-x64\libSkiaSharp.dll"
  File "pino.ico"
  File ".\bin\Release\net8.0\publish\win-x64\ProyectLauncher.pdb"
  File ".\bin\Release\net8.0\publish\win-x64\Launcher.pdb"
  File ".\bin\Release\net8.0\publish\win-x64\Launcher.exe"
  CreateDirectory "$SMPROGRAMS\Pino Launcher"
  CreateShortCut "$SMPROGRAMS\Pino Launcher\Pino Launcher.lnk" "$INSTDIR\Launcher.exe"
  CreateShortCut "$DESKTOP\Pino Launcher.lnk" "$INSTDIR\Launcher.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\Launcher.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\Launcher.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "La desinstalaci�n de $(^Name) finaliz� satisfactoriamente."
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "�Esta seguro de desinstalar $(^Name)?" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\Launcher.exe"
  Delete "$INSTDIR\Launcher.pdb"
  Delete "$INSTDIR\ProyectLauncher.pdb"
  Delete "$INSTDIR\pino.ico"
  Delete "$INSTDIR\libSkiaSharp.dll"
  Delete "$INSTDIR\libHarfBuzzSharp.dll"
  Delete "$INSTDIR\av_libglesv2.dll"

  Delete "$DESKTOP\Pino Launcher.lnk"
  Delete "$SMPROGRAMS\Pino Launcher\Pino Launcher.lnk"

  RMDir "$SMPROGRAMS\Pino Launcher"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd